---
networks:
  bloodbank:
    driver: bridge

services:
  db:
    container_name: mysql
    image: maha110/mysql_bloodbank:v1
    ports:
      - "3306:3306"
    networks:
      - bloodbank

  frontend:
    container_name: php_app
    image: maha110/frontend_bloodbankapp:v1
    networks:
      - bloodbank
    ports:
      - "80:80"
    depends_on:
      - db
      
    
